language: node_js
node_js:
  - "8"
env:
  matrix:
    - PACKAGE=bot-core
    - PACKAGE=stand-bot

install:
  - npm i && lerna bootstrap
script:
  - lerna run tslint --scope $PACKAGE && lerna run build --scope $PACKAGE
