language: node_js
node_js:
  - "8"

env:
  - PACKAGE=bot-core
  - PACKAGE=stand-bot

install:
  - npm i && lerna run build --scope bot-core && lerna bootstrap
script:
  - lerna run tslint --scope $PACKAGE && lerna run build --scope $PACKAGE
